### PR TITLE
Merge jdk 11.0.10 ga

### PR DESCRIPTION
**Pull request by tanghaoth90**

### CODE REVIEW

**Comment by tanghaoth90** [comment]
Conflicts (the result of `git diff` after `git merge`):
```
diff --cc make/lib/Awt2dLibraries.gmk
index 5d4b205a1f0,207a459ae0d..00000000000
--- a/make/lib/Awt2dLibraries.gmk
+++ b/make/lib/Awt2dLibraries.gmk
@@@ -616,13 -688,9 +688,19 @@@ $(eval $(call SetupJdkLibrary, BUILD_LI
      CFLAGS_windows = -DCC_NOEX, \
      EXTRA_HEADER_DIRS := $(LIBFONTMANAGER_EXTRA_HEADER_DIRS), \
      WARNINGS_AS_ERRORS_xlc := false, \
++<<<<<<< HEAD
 +    DISABLED_WARNINGS_gcc := sign-compare int-to-pointer-cast \
 +        type-limits missing-field-initializers implicit-fallthrough strict-aliasing class-memaccess, \
 +    DISABLED_WARNINGS_CXX_gcc := reorder delete-non-virtual-dtor strict-overflow \
 +        maybe-uninitialized, \
 +    DISABLED_WARNINGS_clang := unused-value incompatible-pointer-types \
 +        tautological-constant-out-of-range-compare int-to-pointer-cast, \
 +    DISABLED_WARNINGS_C_solstudio = \
++=======
+     DISABLED_WARNINGS_gcc := sign-compare unused-function int-to-pointer-cast, \
+     DISABLED_WARNINGS_clang := sign-compare, \
+     DISABLED_WARNINGS_C_solstudio := \
++>>>>>>> 0d81ee9872a
          E_INTEGER_OVERFLOW_DETECTED \
          E_ARG_INCOMPATIBLE_WITH_ARG_L \
          E_ENUM_VAL_OVERFLOWS_INT_MAX, \
diff --cc src/hotspot/share/jfr/support/jfrThreadLocal.cpp
index 47bc7ff274a,2f219089c77..00000000000
--- a/src/hotspot/share/jfr/support/jfrThreadLocal.cpp
+++ b/src/hotspot/share/jfr/support/jfrThreadLocal.cpp
@@@ -55,11 -55,11 +55,19 @@@ JfrThreadLocal::JfrThreadLocal() 
    _stack_trace_hash(0),
    _stackdepth(0),
    _entering_suspend_flag(0),
++<<<<<<< HEAD
 +  _dead(false),
 +  _cached_top_frame_bci(max_jint),
 +  _alloc_count(0),
 +  _alloc_count_until_sample(1),
 +  _cached_event_id(MaxJfrEventId) {}
++=======
+   _dead(false) {
+ 
+   Thread* thread = Thread::current_or_null();
+   _parent_trace_id = thread != NULL ? thread->jfr_thread_local()->trace_id() : (traceid)0;
+ }
++>>>>>>> 0d81ee9872a
  
  u8 JfrThreadLocal::add_data_lost(u8 value) {
    _data_lost += value;
diff --cc src/hotspot/share/jfr/support/jfrThreadLocal.hpp
index e99139d2793,410c2a45b1f..00000000000
--- a/src/hotspot/share/jfr/support/jfrThreadLocal.hpp
+++ b/src/hotspot/share/jfr/support/jfrThreadLocal.hpp
@@@ -52,27 -51,7 +52,31 @@@ class JfrThreadLocal 
    mutable u4 _stackdepth;
    volatile jint _entering_suspend_flag;
    bool _dead;
++<<<<<<< HEAD
 +  // Jfr callstack collection relies on vframeStream.
 +  // But the bci of top frame can not be determined by vframeStream in some scenarios.
 +  // For example, in the opto CallLeafNode runtime call of
 +  // OptoRuntime::jfr_fast_object_alloc_C, the top frame bci
 +  // returned by vframeStream is always invalid. This is largely due to the oopmap that
 +  // is not correctly granted ( refer to PhaseMacroExpand::expand_allocate_common to get more details ).
 +  // The opto fast path object allocation tracing occurs in the opto CallLeafNode,
 +  // which has been broken by invalid top frame bci.
 +  // To fix this, we get the top frame bci in opto compilation phase
 +  // and pass it as parameter to runtime call. Our implementation will replace the invalid top
 +  // frame bci with cached_top_frame_bci.
 +  jint _cached_top_frame_bci;
 +  jlong _alloc_count;
 +  jlong _alloc_count_until_sample;
 +  // This field is used to help to distinguish the object allocation request source
 +  // For example, for object allocation slow path, we trace it in CollectedHeap::obj_allocate.
 +  // But in CollectedHeap::obj_allocate, it is impossible to determine where the allocation request
 +  // is from,  which could be from c1, opto, or even interpreter.
 +  // We save this infomation in _event_id, which later can be retrieved in
 +  // CollecetedHeap::obj_allocate to identify the real allocation request source.
 +  JfrEventId _cached_event_id;
++=======
+   traceid _parent_trace_id;
++>>>>>>> 0d81ee9872a
  
    JfrBuffer* install_native_buffer() const;
    JfrBuffer* install_java_buffer() const;
```

**Comment by tanghaoth90** [comment]
commit a947f58296000697199b4e300d3b73bd61c17d8e
Merge: 45cd39d4e79 0d81ee9872a
Author: Hao Tang <albert.th@alibaba-inc.com>
Date:   Tue Feb 2 16:06:48 2021 +0800

    [Merge] Merge tag 'jdk-11.0.10-ga'
    
    Summary: Merge tag 'jdk-11.0.10-ga'
    
    Reviewed-by: linade, mmyxym
    
    Test Plan: run build on adopt pipeline
    
    Issue: https://github.com/alibaba/dragonwell11/issues/54
```
diff --cc make/lib/Awt2dLibraries.gmk
index 5d4b205a1f0,207a459ae0d..5e8fa42d0ba
--- a/make/lib/Awt2dLibraries.gmk
+++ b/make/lib/Awt2dLibraries.gmk
@@@ -616,13 -688,9 +688,9 @@@ $(eval $(call SetupJdkLibrary, BUILD_LI
      CFLAGS_windows = -DCC_NOEX, \
      EXTRA_HEADER_DIRS := $(LIBFONTMANAGER_EXTRA_HEADER_DIRS), \
      WARNINGS_AS_ERRORS_xlc := false, \
-     DISABLED_WARNINGS_gcc := sign-compare int-to-pointer-cast \
-         type-limits missing-field-initializers implicit-fallthrough strict-aliasing class-memaccess, \
-     DISABLED_WARNINGS_CXX_gcc := reorder delete-non-virtual-dtor strict-overflow \
-         maybe-uninitialized, \
-     DISABLED_WARNINGS_clang := unused-value incompatible-pointer-types \
-         tautological-constant-out-of-range-compare int-to-pointer-cast, \
-     DISABLED_WARNINGS_C_solstudio = \
 -    DISABLED_WARNINGS_gcc := sign-compare unused-function int-to-pointer-cast, \
++    DISABLED_WARNINGS_gcc := sign-compare unused-function int-to-pointer-cast class-memaccess, \
+     DISABLED_WARNINGS_clang := sign-compare, \
+     DISABLED_WARNINGS_C_solstudio := \
          E_INTEGER_OVERFLOW_DETECTED \
          E_ARG_INCOMPATIBLE_WITH_ARG_L \
          E_ENUM_VAL_OVERFLOWS_INT_MAX, \
diff --cc src/hotspot/share/jfr/recorder/stacktrace/jfrStackTrace.cpp
index e916503a09b,64b7b65c53f..37b19dc2160
--- a/src/hotspot/share/jfr/recorder/stacktrace/jfrStackTrace.cpp
+++ b/src/hotspot/share/jfr/recorder/stacktrace/jfrStackTrace.cpp
@@@ -283,21 -253,11 +287,23 @@@ bool JfrStackTrace::fill_in(vframeStrea
      }
      else {
        bci = vfs.bci();
 +      // Hit the top frame and fix bci here.
 +      if (!top_frame_visited) {
 +        if (mode == WALK_BY_CURRENT_FRAME) {
 +          // Only fix opto fast path allocation.
 +          // All fast path allocations do not have cached event id.
 +          if (!vfs.thread_ref()->jfr_thread_local()->has_cached_event_id()) {
 +            assert(vfs.thread_ref()->jfr_thread_local()->has_cached_top_frame_bci(), "Invariant");
 +            bci = vfs.thread_ref()->jfr_thread_local()->cached_top_frame_bci();
 +          }
 +        }
 +        top_frame_visited = true;
 +      }
      }
      // Can we determine if it's inlined?
-     _hash = (_hash << 2) + (unsigned int)(((size_t)mid >> 2) + (bci << 4) + type);
+     _hash = (_hash * 31) + mid;
+     _hash = (_hash * 31) + bci;
+     _hash = (_hash * 31) + type;
      _frames[count] = JfrStackFrame(mid, bci, type, method);
      vfs.next();
      count++;
diff --cc src/hotspot/share/jfr/support/jfrThreadLocal.cpp
index 47bc7ff274a,2f219089c77..db247fd39ef
--- a/src/hotspot/share/jfr/support/jfrThreadLocal.cpp
+++ b/src/hotspot/share/jfr/support/jfrThreadLocal.cpp
@@@ -55,11 -55,11 +55,15 @@@ JfrThreadLocal::JfrThreadLocal() 
    _stack_trace_hash(0),
    _stackdepth(0),
    _entering_suspend_flag(0),
 -  _dead(false) {
 +  _dead(false),
 +  _cached_top_frame_bci(max_jint),
 +  _alloc_count(0),
 +  _alloc_count_until_sample(1),
-   _cached_event_id(MaxJfrEventId) {}
++  _cached_event_id(MaxJfrEventId) {
+ 
+   Thread* thread = Thread::current_or_null();
+   _parent_trace_id = thread != NULL ? thread->jfr_thread_local()->trace_id() : (traceid)0;
+ }
  
  u8 JfrThreadLocal::add_data_lost(u8 value) {
    _data_lost += value;
diff --cc src/hotspot/share/jfr/support/jfrThreadLocal.hpp
index e99139d2793,410c2a45b1f..b4edbbe1edb
--- a/src/hotspot/share/jfr/support/jfrThreadLocal.hpp
+++ b/src/hotspot/share/jfr/support/jfrThreadLocal.hpp
@@@ -52,27 -51,7 +52,28 @@@ class JfrThreadLocal 
    mutable u4 _stackdepth;
    volatile jint _entering_suspend_flag;
    bool _dead;
+   traceid _parent_trace_id;
 +  // Jfr callstack collection relies on vframeStream.
 +  // But the bci of top frame can not be determined by vframeStream in some scenarios.
 +  // For example, in the opto CallLeafNode runtime call of
 +  // OptoRuntime::jfr_fast_object_alloc_C, the top frame bci
 +  // returned by vframeStream is always invalid. This is largely due to the oopmap that
 +  // is not correctly granted ( refer to PhaseMacroExpand::expand_allocate_common to get more details ).
 +  // The opto fast path object allocation tracing occurs in the opto CallLeafNode,
 +  // which has been broken by invalid top frame bci.
 +  // To fix this, we get the top frame bci in opto compilation phase
 +  // and pass it as parameter to runtime call. Our implementation will replace the invalid top
 +  // frame bci with cached_top_frame_bci.
 +  jint _cached_top_frame_bci;
 +  jlong _alloc_count;
 +  jlong _alloc_count_until_sample;
 +  // This field is used to help to distinguish the object allocation request source
 +  // For example, for object allocation slow path, we trace it in CollectedHeap::obj_allocate.
 +  // But in CollectedHeap::obj_allocate, it is impossible to determine where the allocation request
 +  // is from,  which could be from c1, opto, or even interpreter.
 +  // We save this infomation in _event_id, which later can be retrieved in
 +  // CollecetedHeap::obj_allocate to identify the real allocation request source.
 +  JfrEventId _cached_event_id;
  
    JfrBuffer* install_native_buffer() const;
    JfrBuffer* install_java_buffer() const;
diff --cc src/hotspot/share/prims/jvm.cpp
index 24c66ab3918,df5d1e51db7..61383434918
--- a/src/hotspot/share/prims/jvm.cpp
+++ b/src/hotspot/share/prims/jvm.cpp
@@@ -2923,6 -2924,15 +2924,15 @@@ JVM_ENTRY(void, JVM_StartThread(JNIEnv
                os::native_thread_creation_failed_msg());
    }
  
+ #if INCLUDE_JFR
+   if (JfrRecorder::is_recording() && EventThreadStart::is_enabled() &&
+       EventThreadStart::is_stacktrace_enabled()) {
+     JfrThreadLocal* tl = native_thread->jfr_thread_local();
+     // skip Thread.start() and Thread.start0()
 -    tl->set_cached_stack_trace_id(JfrStackTraceRepository::record(thread, 2));
++    tl->set_cached_stack_trace_id(JfrStackTraceRepository::record(thread, 2, WALK_BY_DEFAULT));
+   }
+ #endif
+ 
    Thread::start(native_thread);
  
  JVM_END
```

**Review by D-D-H — APPROVED** [review]
JFR part looks good to me.

**Review by sandlerwang — APPROVED** [review]
The changed building flags do not affect aarch64

**Review by mmyxym — APPROVED** [review]

**Pull request merged**
